### ISSUE TITLE
e2e tests fail on restic 0.15.0

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/resticpy#123]
It looks like there was a behavior change regarding the `key` commands between restic 0.14.0 and 0.15.0:

```text
restic.internal.command_executor DEBUG Executing restic command: ['restic', '--json', '--repo', '/tmp/tmptb08eehk', '--password-file', '/tmp/tmpd8d2zsg5', 'key', 'add', '--new-password-file', '/tmp/tmpwc_bfxa7']
restic.internal.command_executor DEBUG Restic command completed with return code 0
__main__        INFO adding a repo key: saved new key as <Key of circleci@2c1148e47051, created on 2023-01-18 13:25:18.0799674 +0000 UTC m=+2.601499347>

restic.internal.command_executor DEBUG Executing restic command: ['restic', '--json', '--repo', '/tmp/tmptb08eehk', '--password-file', '/tmp/tmpd8d2zsg5', 'key', 'list']
restic.internal.command_executor DEBUG Restic command completed with return code 0
__main__        INFO after changing key, repo keys: [{'current': False, 'id': 'c660bf8b', 'userName': 'circleci', 'hostName': '2c1148e47051', 'created': '2023-01-18 13:25:18'}, {'current': True, 'id': '8d4fc78d', 'userName': 'circleci', 'hostName': '2c1148e47051', 'created': '2023-01-18 13:25:10'}]
restic.internal.command_executor DEBUG Executing restic command: ['restic', '--json', '--repo', '/tmp/tmptb08eehk', '--password-file', '/tmp/tmpwc_bfxa7', 'key', 'passwd', '--new-password-file', '/tmp/tmppkuhmvah']
restic.internal.command_executor DEBUG Restic command completed with return code 0
__main__        INFO changing repo default key: saved new key as <Key of circleci@2c1148e47051, created on 2023-01-18 13:25:23.068754915 +0000 UTC m=+3.307467852>

restic.internal.command_executor DEBUG Executing restic command: ['restic', '--json', '--repo', '/tmp/tmptb08eehk', '--password-file', '/tmp/tmpd8d2zsg5', 'key', 'list']
restic.internal.command_executor DEBUG Restic command completed with return code 0
__main__        INFO after changing key, repo keys: [{'current': False, 'id': '9d82ccba', 'userName': 'circleci', 'hostName': '2c1148e47051', 'created': '2023-01-18 13:25:23'}, {'current': True, 'id': '8d4fc78d', 'userName': 'circleci', 'hostName': '2c1148e47051', 'created': '2023-01-18 13:25:10'}]
restic.internal.command_executor DEBUG Executing restic command: ['restic', '--json', '--repo', '/tmp/tmptb08eehk', '--password-file', '/tmp/tmpd8d2zsg5', 'key', 'remove', '8d4fc78d']
restic.internal.command_executor DEBUG Restic command completed with return code 1
Traceback (most recent call last):
  File "./e2e/test.py", line 137, in <module>
    restic.key.remove(repo_keys[1]['id']))
  File "/home/circleci/project/venv/lib/python3.7/site-packages/restic/internal/key.py", line 34, in remove
    return command_executor.execute(cmd)
  File "/home/circleci/project/venv/lib/python3.7/site-packages/restic/internal/command_executor.py", line 27, in execute
    process.stderr)
restic.errors.ResticFailedError: Restic failed with exit code 1: Fatal: refusing to remove key currently used to access repository
```

https://app.circleci.com/pipelines/github/mtlynch/resticpy/352/workflows/3505fb9c-ac17-4af5-bff5-371005893d5e/jobs/1007

It looks like in 0.14.0, the `restic key passwd` command implicitly changed the new key to be the default repo key, but in 0.15.0, it just replaces the first key in the list instead, which may not be the default.

See #116

**Comment by mtlynch** [comment]
@baurmatt - Do you have any ideas on how to solve this one?

**Comment by baurmatt** [comment]
This looks to be related to https://github.com/restic/restic/pull/3971

It introduces parallel key retrieval on `key list`.

This test seems to prove it:

```
$ for i in {1..5}; do restic key list;done
repository 14dc92bd opened (version 2, compression level auto)
 ID        User   Host   Created
--------------------------------------------
*45636721  mbaur  mbaur  2023-01-20 11:56:18
 61b215b7  mbaur  mbaur  2023-01-20 11:57:13
--------------------------------------------
repository 14dc92bd opened (version 2, compression level auto)
 ID        User   Host   Created
--------------------------------------------
 61b215b7  mbaur  mbaur  2023-01-20 11:57:13
*45636721  mbaur  mbaur  2023-01-20 11:56:18
--------------------------------------------
repository 14dc92bd opened (version 2, compression level auto)
 ID        User   Host   Created
--------------------------------------------
 61b215b7  mbaur  mbaur  2023-01-20 11:57:13
*45636721  mbaur  mbaur  2023-01-20 11:56:18
--------------------------------------------
repository 14dc92bd opened (version 2, compression level auto)
 ID        User   Host   Created
--------------------------------------------
 61b215b7  mbaur  mbaur  2023-01-20 11:57:13
*45636721  mbaur  mbaur  2023-01-20 11:56:18
--------------------------------------------
repository 14dc92bd opened (version 2, compression level auto)
 ID        User   Host   Created
--------------------------------------------
*45636721  mbaur  mbaur  2023-01-20 11:56:18
 61b215b7  mbaur  mbaur  2023-01-20 11:57:13
--------------------------------------------
``` 

-> The position of the active key changes.

I've opened #124 to fix this.
